//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SayWellcome", ReplyAction="http://tempuri.org/IService/SayWellcomeResponse")]
        string SayWellcome();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SayWellcome", ReplyAction="http://tempuri.org/IService/SayWellcomeResponse")]
        System.Threading.Tasks.Task<string> SayWellcomeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ExecuteCommand", ReplyAction="http://tempuri.org/IService/ExecuteCommandResponse")]
        string ExecuteCommand(string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ExecuteCommand", ReplyAction="http://tempuri.org/IService/ExecuteCommandResponse")]
        System.Threading.Tasks.Task<string> ExecuteCommandAsync(string command);
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/IService/EndSession", ReplyAction="http://tempuri.org/IService/EndSessionResponse")]
        void EndSession();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/IService/EndSession", ReplyAction="http://tempuri.org/IService/EndSessionResponse")]
        System.Threading.Tasks.Task EndSessionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : RemoteClient.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RemoteClient.ServiceReference1.IService>, RemoteClient.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayWellcome() {
            return base.Channel.SayWellcome();
        }
        
        public System.Threading.Tasks.Task<string> SayWellcomeAsync() {
            return base.Channel.SayWellcomeAsync();
        }
        
        public string ExecuteCommand(string command) {
            return base.Channel.ExecuteCommand(command);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteCommandAsync(string command) {
            return base.Channel.ExecuteCommandAsync(command);
        }
        
        public void EndSession() {
            base.Channel.EndSession();
        }
        
        public System.Threading.Tasks.Task EndSessionAsync() {
            return base.Channel.EndSessionAsync();
        }
    }
}
